version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.3
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
  kafka:
    image: confluentinc/cp-kafka:7.3.3
    container_name: my-kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://my-kafka:29092,PLAINTEXT_HOST://my-kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  author:
    depends_on:
      - kafka
    image: "docker name"/author
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - 8082:8082

  write:
    depends_on:
      - kafka
    image: "docker name"/write
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - 8083:8083

  books:
    depends_on:
      - kafka
    image: "docker name"/books
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - 8084:8084

  subscription:
    depends_on:
      - kafka
    image: "docker name"/subscription
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - 8085:8085

  user:
    depends_on:
      - kafka
    image: "docker name"/user
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - 8086:8086

  point:
    depends_on:
      - kafka
    image: "docker name"/point
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - 8087:8087

  generation:
    depends_on:
      - kafka
    image: "docker name"/generation
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - OPENAI_API_KEY=${OPENAI_API_KEY:-sk-dummy-key-for-testing}
    ports:
      - 8088:8088

  gateway:
    depends_on:
      - kafka
    image: "docker name"/gateway
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - 8080:8080

  purchase:
    depends_on:
      - kafka
    image: "docker name"/purchase
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - 8089:8089

      #  usercenter:
      #    depends_on:
      #      - kafka
      #    image: "docker name"/maven-openjdk11:latest
      #    environment:
      #      - SPRING_PROFILES_ACTIVE=docker
      #    command: mvn spring-boot:run
      #    ports:
      #      - 8090:8090
      #    working_dir: /usr/src
      #    volumes:
      #      - ./usercenter:/usr/src
      #      - ./maven-repo:/root/.m2

  read:
    depends_on:
      - kafka
    image: "docker name"/read
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - 8091:8091
