apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: "project09.azurecr.io/frontend:250702"
          ports:
            - containerPort: 8080
          
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10 
            periodSeconds: 5      
            timeoutSeconds: 2
            failureThreshold: 3
          
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30 
            periodSeconds: 10    
            timeoutSeconds: 2
            failureThreshold: 3
            