apiVersion: apps/v1
kind: Deployment
metadata:
  name: usercenter
  labels:
    app: usercenter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: usercenter
  template:
    metadata:
      labels:
        app: usercenter
    spec:
      containers:
        - name: usercenter
          image: "project09.azurecr.io/aivle-msa/usercenter:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
